### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by snaildos** [Lemons1337/Discord-Spammer#11]
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'C:\Users\zaras.LAPTOP-NPONEGMA\Desktop\folders\snaildos BOT\spammer\discord-spam-bots-master\discord-spam-bots-master\index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

What happend?

**Comment by ItsLachy** [comment]
You never installed your dependencies.

**Comment by snaildos** [comment]
What are the dependencies, I cant see any...

**Comment by boob** [comment]
Do npm install

**Comment by snaildos** [comment]
Ye, its working now, but when I send a bot it says "Sent 0 bots"
Why is that??

**Comment by boob** [comment]
You dont have any working tokens

**Comment by snaildos** [comment]
I do, Its the bot token "Testing Bot"

**Comment by boob** [comment]
Not bot tokens, by tokens it means tokens of real profiles.
This doesn't send bots, it sends real profiles.

**Comment by snaildos** [comment]
Oh, I see, Thanks!
